apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Hemanth148909/myapp-argocd.git
    path: argocd-app
    targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: maint

  syncPolicy:
    automated:
      selfHeal: true
      prune: true

    syncOptions:
      - CreateNamespace=true
ignoreDifferences:
  - group: apps
    kind: statefulset
    jsonPointers:
      - /spec/replicas      