apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

      # 🔥 This is the key: changes every commit = triggers rollout
      annotations:
        redeployTimestamp: "${GIT_COMMIT_SHA}"

    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
