apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 25
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

      # 🔥 This is the key: changes every commit = triggers rollout
      annotations:
        redeployTimestamp: "fa31d7e28955738db770a963463004fb3f7f3400"

    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
