name: Update Deployment Manually

on:
  workflow_dispatch:   # 🔥 manual trigger from GitHub UI

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Inject commit SHA
      run: |
        sed -i "s|\${GIT_COMMIT_SHA}|${GITHUB_SHA}|g" argocd-app/deployment.yaml

    - name: Commit updated manifest
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add argocd-app/deployment.yaml
        git commit -m "Manual redeploy trigger" || echo "No changes"
        git push
